# Install Docker Engine and Docker Compose
# https://docs.docker.com/engine/install/ubuntu/
# https://docs.docker.com/compose/install/linux/

- name: Uninstall old versions
  become: yes
  apt:
    pkg:
      - 'containerd'
      - 'docker'
      - 'docker.io'
      - 'docker-compose'
      - 'docker-compose-v2'
      - 'docker-doc'
      - 'docker-engine'
      - 'padman-docker'
      - 'runc'
    state: absent

- name: Set up the repository
  become: yes
  apt:
    pkg:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'gnupg'
      - 'lsb-release'
      - 'software-properties-common'
      update_cache: yes

- name: Create /etc/apt/keyrings directory
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Dockers official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    file: /etc/apt/keyrings/docker.asc

- name: Ensure /etc/apt/keyrings/docker.asc has read permissions for all users
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Set ubuntu architecture
  command: dpkg --print-architecture
  register: architecture

- name: Set ubuntu codename
  command: . /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"
  register: codename

- name: Set up the stable repository
  become: yes
  apt_repository:
    repo: deb [arch="{{ architecture.stdout }}" signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu "{{ codename.stdout }}" stable

- name: Install Docker Engine
  become: yes
  apt:
    pkg:
      - 'docker-ce'
      - 'docker-ce-cli'
      - 'containerd.io'
      - 'docker-buildx-plugin'
      - 'docker-compose-plugin'
    update_cache: yes

- name: Add "{{ username }}" to docker group
  become: yes
  user:
    name: "{{ username }}"
    groups: docker
