- name: Uninstall old versions
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
    state: absent

- name: Set up the repository
  become: yes
  apt:
    name: ['ca-certificates', 'curl', 'gnupg', 'lsb-release']
    update_cache: yes

- name: Add Dockers official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Verify that we have the key with the fingerprint
  become: yes
  apt_key:
    id: 0EBFCD88

- name: Set ubuntu codename
  command: lsb_release -cs
  register: codename

- name: Set up the stable repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ codename.stdout }}" stable

- name: Install Docker Engine
  become: yes
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: yes

- name: Add "{{ username }}" to docker group
  become: yes
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Set os
  command: uname -s
  register: os

- name: Set architecture
  command: uname -m
  register: architecture

- name: Install docker-compose
  become: yes
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.28.0/docker-compose-{{ os.stdout }}-{{ architecture.stdout }}"
    dest: /usr/local/bin/docker-compose
    force: yes

- name: Apply executable permissions
  become: yes
  file:
    path: /usr/local/bin/docker-compose
    mode: +x

