- name: Add terraforms official GPG key
  become: yes
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: Set ubuntu codename
  command: lsb_release -cs
  register: codename

- name: Set up the stable repository
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com "{{ codename.stdout }}" main'

- name: Install terraform
  become: yes
  apt:
    name: terraform
    update_cache: yes
    state: latest
