- name: Uninstall old versions
  become: yes
  dnf:
    name:
    - 'docker'
    - 'docker-client'
    - 'docker-client-latest'
    - 'docker-common'
    - 'docker-latest'
    - 'docker-latest-logrotate'
    - 'docker-selinux'
    - 'docker-engine-selinux'
    - 'docker-engine'
    state: absent

- name: Install dnf-plugins-core
  become: yes
  dnf:
    name: dnf-plugins-core
    update_cache: yes
    state: present

- name: Install docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  # https://github.com/ansible/ansible/issues/46963
  # dnf: support config-manager plugin for repository management 

- name: Set up the repository
  become: yes
  dnf:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
    update_cache: yes
    state: present

- name: Add "{{ username }}" to docker group
  become: yes
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

