- name: Install dnf-plugins-core
  become: yes
  dnf:
    name: dnf-plugins-core
    update_cache: yes
    state: latest

- name: Add the repository

- name: Install terraform
  become: yes
  dnf:
    name: terraform
    update_cache: yes
    state: latest
