- name: Clone dotfiles repo
  git:
    repo: 'https://github.com/faultier92/dotfiles.git'
    dest: ~/projects/dotfiles
    clone: yes
    update: yes
    force: yes

- name: Change file permissions
  file:
    path: "/home/{{ username }}/projects/dotfiles/scripts/setup.sh" 
    mode: '0700'

- name: Setup dotfiles
  shell:
    cmd: ./scripts/setup.sh
    chdir: "/home/{{ username }}/projects/dotfiles"

